#http://localhost:8888/api/v1/graph/label/node/title/autoComplete?title=深圳
#http://localhost:8888/dev-api/v1/graph/tree/node?id=4de489c5-cc7f-4d32-8970-679554f66e5b

#http://localhost:8888/dev-api/v1/graph/tree/node/company/title/autoComplete?keyWord=深圳
#http://localhost:8888/dev-api/v1/graph/tree/path/company/title/fuzzyMatch?keyWord=深圳
#http://localhost:8888/dev-api/v1/graph/tree/node/label/title/autoComplete?keyWord=高新



# task:


#http://127.0.0.1:8888/api/v1/rskc/origin-content/task/sync

#http://127.0.0.1:8888/api/v1/rskc/trades-detail/task/sync

#http://127.0.0.1:8888/api/v1/rskc/trades-detail/task/sync-wait
#
#http://127.0.0.1:8888/api/v1/spider/enterprise/wait-list/task/check-integrality

http://127.0.0.1:8888/api/v1/rskc/origin-content/task/sync-dependencies