settings:
  application:
    enabledp: true
    host: 0.0.0.0
    mode: prod
    name: testApp
    port: 8888
    readtimeout: 100
    writertimeout: 200
  database:
    driver: mysql
    source: root:oyyufei8@tcp(192.168.44.169:3306)/go_admin?charset=utf8mb4&parseTime=True&loc=Local&timeout=10000ms
    registers:
      - sources:
          - 'root:oyyufei8@tcp(192.168.44.169:3306)/data_spider?charset=utf8mb4&parseTime=True&loc=Local&timeout=10000ms'
        replicas:
          - 'root:oyyufei8@tcp(192.168.44.169:3306)/data_spider?charset=utf8mb4&parseTime=True&loc=Local&timeout=10000ms'
        tables:
          - 'enterprise_wait_list'
          - 'enterprise'
          - 'enterprise_info'
          - 'enterprise_industry'
          - 'enterprise_certification'
          - 'enterprise_ranking'
          - 'enterprise_product'
          - 'ranking_list'
          - 'rc_origin_content'
          - 'rc_trades_detail'
          - 'rc_processed_content'
          - 'task_detail'
          - 'rc_dependency_data'
          - 'rc_selling_sta'
          - 'rc_decision_param'
          - 'rc_decision_result'
          - 'rc_i18n_content'
          - 'rc_report_oss'
          - 'oss_metadata'
          - 'rc_scorecard'
          - 'rc_scorecard_rule'
          - 'rc_scorecard_result'
  gen:
    dbname: go_admin
    frontpath: ../graphAdminWebserver/src
  jwt:
    secret: go-admin
    timeout: 3600
  logger:
    # 日志存放路径
    path: temp/logs
    # 日志输出，file：文件，default：命令行，其他：命令行
    stdout: '' #控制台日志，启用后，不输出到文件
    # 日志等级, trace, debug, info, warn, error, fatal
    level: trace
    # 数据库日志开关
    enableddb: true
  queue:
    memory:
      poolSize: 100
  extend:
    amap:
      key:
    graph:
      neo4j:
        activate: true
        uri: neo4j://192.168.44.169:7687
        username: neo4j
        password: password
    vzoom:
      sftp:
        host: 120.132.117.50
        port: '8155'
        username: lhgyl
        password: lhgyl2022
      decisionEngine:
        uri: "http://10.0.203.188:8086"
    nats:
      uri: "nats://dev:password@192.168.44.169:4222"
      activate: true
    minio:
      endpoint: 192.168.44.169:9030
      accessKey: wuUZssvlpfRvYESyaT1J
      secretKey: IdieLkzlLD3hWlVitGyswHcnoXWdnR6z7q5qaDvv
      useSsl: false
      activate: true
    pdfConvert:
      gtb:
        server: http://192.168.44.169:3033
      report:
        server: http://192.168.44.150:1024
        path: /login?redirect=/CrawlReport
        username: admin
        password: "1234"
        ossBucketName: "rcreport"
    pySidecar:
      server: http://192.168.31.158:8001
      ahpPath: /ahp
