settings:
  application:
    enabledp: true
    host: 0.0.0.0
    mode: prod
    name: Brillink数据中台
    port: 8890
    readtimeout: 100
    writertimeout: 200
  database:
    driver: mysql
    source: blscf:Dzkw46MZDbB7axDC@tcp(10.0.232.121:3308)/bl_data_admin?charset=utf8mb4&parseTime=True&loc=Local&timeout=10000ms
    registers:
      - sources:
          - 'blscf:Dzkw46MZDbB7axDC@tcp(10.0.232.121:3308)/bl_business?charset=utf8mb4&parseTime=True&loc=Local&timeout=10000ms'
        replicas:
          - 'blscf:Dzkw46MZDbB7axDC@tcp(10.0.232.121:3308)/bl_business?charset=utf8mb4&parseTime=True&loc=Local&timeout=10000ms'
        tables:
          - 'enterprise_wait_list'
          - 'enterprise'
          - 'enterprise_info'
          - 'enterprise_industry'
          - 'enterprise_certification'
          - 'enterprise_ranking'
          - 'enterprise_product'
          - 'ranking_list'
          - 'rc_origin_content'
          - 'rc_trades_detail'
          - 'rc_processed_content'
          - 'task_detail'
          - 'rc_selling_sta'
          - 'rc_decision_param'
          - 'rc_decision_result'
          - 'rc_i18n_content'
          - 'rc_dependency_data'
          - 'rc_report_oss'
          - 'oss_metadata'
  gen:
    dbname: bl_data_admin
    frontpath: ../graphAdminWebserver/src
  jwt:
    secret: bl-data-admin
    timeout: 3600
  logger:
    # 日志存放路径
    path: temp/logs
    # 日志输出，file：文件，default：命令行，其他：命令行
    stdout: '' #控制台日志，启用后，不输出到文件
    # 日志等级, trace, debug, info, warn, error, fatal
    level: trace
    # 数据库日志开关
    enableddb: true
  queue:
    memory:
      poolSize: 100
  extend:
    amap:
      key:
    graph:
      neo4j:
        activate: true
        uri: neo4j://10.0.232.121:7687
        username: neo4j
        password: bl@neo4j
    vzoom:
      sftp:
        host: 120.132.117.50
        port: '8155'
        username: lhgyl
        password: lhgyl2022
      decisionEngine:
        uri: "http://10.0.203.188:8086"
    nats:
      uri: "nats://brillinkdata:MFmi9jAB@10.0.232.121:4222"
      activate: true
    minio:
      endpoint: 10.0.232.121:9030
      accessKey: ys0whFZv98wtOgyXIRBS
      secretKey: AZ6M7FVo4ZlkPvDZWAweSXIueUqqQ2ujITlvvmdq
      useSsl: false
      activate: true
    pdfConvert:
      gtb:
        server: http://10.0.232.22:3033
      report:
        server: http://192.168.44.150:1024
        path: /login?redirect=/CrawlReport
        username: admin
        password: "1234"
        ossBucketName: "report-snapshot"
