settings:
  application:
    enabledp: true
    host: 0.0.0.0
    mode: dev
    name: testApp
    port: 8888
    readtimeout: 100
    writertimeout: 200
  database:
    driver: mysql
    source: root:adminpassword@tcp(192.168.31.158:3306)/brillink_admin?charset=utf8mb4&parseTime=True&loc=Local&timeout=10000ms
    registers:
      - sources:
          - 'root:adminpassword@tcp(192.168.31.158:3306)/data_warehouse?charset=utf8mb4&parseTime=True&loc=Local&timeout=10000ms'
        replicas:
          - 'root:adminpassword@tcp(192.168.31.158:3306)/data_warehouse?charset=utf8mb4&parseTime=True&loc=Local&timeout=10000ms'
        tables:
          - 'enterprise_wait_list'
          - 'enterprise'
          - 'enterprise_info'
          - 'enterprise_industry'
          - 'enterprise_certification'
          - 'enterprise_ranking'
          - 'enterprise_product'
          - 'ranking_list'
          - 'rc_origin_content'
          - 'rc_trades_detail'
          - 'rc_processed_content'
          - 'task_detail'
          - 'rc_selling_sta'
          - 'rc_decision_param'
          - 'rc_decision_result'
          - 'rc_i18n_content'
          - 'rc_dependency_data'
  gen:
    dbname: brillink_admin
    frontpath: ../graphAdminWebserver/src
  jwt:
    secret: go-admin
    timeout: 3600
  logger:
    # 日志存放路径
    path: temp/logs
    # 日志输出，file：文件，default：命令行，其他：命令行
    stdout: '' #控制台日志，启用后，不输出到文件
    # 日志等级, trace, debug, info, warn, error, fatal
    level: trace
    # 数据库日志开关
    enableddb: true
  queue:
    memory:
      poolSize: 100
  extend:
    nats:
      uri: "nats://dev:password@192.168.31.158:4222"
      activate: true
    vzoom:
      sftp:
        host: 192.168.31.158
        port: '2222'
        username: admin
        password: password
    graph:
      neo4j:
        activate: true
        uri: neo4j://192.168.31.158:7687
        username: neo4j
        password: password
    amap:
      key:
    minio:
      endpoint: 192.168.31.158:9030
      accessKey: bSDUxn0uQYn0xHfZ2mpZ
      secretKey: cympip-rifraB-vuzra2
      use_ssl: false
      activate: true
    pdf_convert:
      gtb:
        server: 192.168.31.158:3000
      report:
        server: 192.168.31.158:9030
        path: /report/snapshot
        username: admin
        password: "1234"
        oss_bucket_name: "report_snapshot"
